### ISSUE TITLE
[need help] tracking windows, arm64, aarch64, ppc64le builds

### ISSUE THREAD

**Issue by ngam** [conda-forge/julia-feedstock#162]
We plan to build for windows, arm64, aarch64, and ppc64le soon. This issue is a central place to track the development on that front. More details soon once we get some other work out of the way.

---

TODO:

- [ ] windows (#168)
- [ ] arm64
- [ ] aarch
- [ ] ppc

---

Current known bottlenecks on the arm/aarch front:

- [x] openlibm (clear!)
- [x] mbedtls (https://github.com/conda-forge/mbedtls-feedstock)
- [ ]  openblas-ilp64 (starting point: https://github.com/conda-forge/julia-feedstock/pull/157#issuecomment-1001370996 and see this: https://github.com/conda-forge/openblas-feedstock/issues/131)
- [x] p7zip (https://github.com/conda-forge/p7zip-feedstock/pull/2 and https://github.com/conda-forge/p7zip-feedstock/pull/3)

---

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>
